In [1]:
import torch
import torch.nn.functional as F
import math

torch.manual_seed(42)

# ------------------------------------------------------------
# 1. Toy sentence
# ------------------------------------------------------------

sentence = "i am driving"
words = sentence.split()

vocab = sorted(set(words))
stoi = {word: i for i, word in enumerate(vocab)}
itos = {i: word for word, i in stoi.items()}

x_ids = torch.tensor([stoi[word] for word in words])

print("Vocabulary:", stoi)
print("Input ids:", x_ids)

# ------------------------------------------------------------
# 2. Manual embedding table
# ------------------------------------------------------------

vocab_size = len(vocab)
embedding_dim = 4

E = torch.ones(vocab_size, embedding_dim)

# X shape: [T, embedding_dim]
X = E[x_ids]

print("\nX shape:", X.shape)
print("X:")
print(X)

# ------------------------------------------------------------
# 3. Self-attention parameters
# ------------------------------------------------------------

d_model = embedding_dim
d_k = 4
d_v = 4

W_Q = torch.randn(d_model, d_k) * 0.1
W_K = torch.randn(d_model, d_k) * 0.1
W_V = torch.randn(d_model, d_v) * 0.1

# ------------------------------------------------------------
# 4. Create Q, K, V from the SAME input sequence X
# ------------------------------------------------------------

Q = X @ W_Q   # [T, d_k]
K = X @ W_K   # [T, d_k]
V = X @ W_V   # [T, d_v]

print("\nQ shape:", Q.shape)
print("K shape:", K.shape)
print("V shape:", V.shape)

# ------------------------------------------------------------
# 5. Attention scores
# ------------------------------------------------------------

# Q @ K.T:
# [T, d_k] @ [d_k, T] = [T, T]
scores = Q @ K.T

# Scale by sqrt(d_k)
scores = scores / math.sqrt(d_k)

print("\nRaw attention scores shape:", scores.shape)
print(scores)

# ------------------------------------------------------------
# 6. Attention weights
# ------------------------------------------------------------

# softmax row-wise:
# each token decides how much to attend to every token
attention_weights = F.softmax(scores, dim=1)

print("\nAttention weights:")
print(attention_weights)

# ------------------------------------------------------------
# 7. Weighted sum of values
# ------------------------------------------------------------

# [T, T] @ [T, d_v] = [T, d_v]
output = attention_weights @ V

print("\nSelf-attention output shape:", output.shape)
print(output)

# ------------------------------------------------------------
# 8. Print readable attention table
# ------------------------------------------------------------

print("\nAttention table:")
header = f"{'from/to':>10s}"
for word in words:
    header += f"{word:>12s}"
print(header)

for i, from_word in enumerate(words):
    row = f"{from_word:>10s}"
    for weight in attention_weights[i]:
        row += f"{float(weight):12.3f}"
    print(row)

Vocabulary: {'am': 0, 'driving': 1, 'i': 2}
Input ids: tensor([2, 0, 1])

X shape: torch.Size([3, 4])
X:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Q shape: torch.Size([3, 4])
K shape: torch.Size([3, 4])
V shape: torch.Size([3, 4])

Raw attention scores shape: torch.Size([3, 3])
tensor([[-0.0689, -0.0689, -0.0689],
        [-0.0689, -0.0689, -0.0689],
        [-0.0689, -0.0689, -0.0689]])

Attention weights:
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])

Self-attention output shape: torch.Size([3, 4])
tensor([[-0.3898,  0.1823, -0.2032, -0.0146],
        [-0.3898,  0.1823, -0.2032, -0.0146],
        [-0.3898,  0.1823, -0.2032, -0.0146]])

Attention table:
   from/to           i          am     driving
         i       0.333       0.333       0.333
        am       0.333       0.333       0.333
   driving       0.333       0.333       0.333


In [5]:
import torch.nn as nn
x = torch.tensor(torch.arange(1, 100, 0.1))
y = x **2



class regression_model(nn.Module):
    def __init__(self):
        self.h = nn.Linear(in_features=1, out_features=2)
        self.lh = nn.Linear(in_features=2, out_features=1)

    def forward(self, x, y):
        x_out = self.h(x)
        x_out = self.lh(x_out)

        loss = F.mse_loss(x_out, y)

        return x_out, loss
        
reg_model = regression_model()

opt = torch.optim.SGD(reg_model.parameters(), lr=0.001)

for epoch in range(100):
    opt.zero_grad()

    for input, target in zip(x, y):    
        predictions, loss = reg_model(input, target)

        loss.backward()

        opt.step()

        if (epoch + 1) % 20 == 0:
            print(f"Epoch [{epoch+1}/100], Loss: {loss.item():.4f}")

/tmp/ipykernel_2815203/2825963910.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(torch.arange(1, 100, 0.1))


AttributeError: cannot assign module before Module.__init__() call