In [2]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import random

In [2]:
e = torch.randn(32, 4, 68)      # 32 examples, 4 characters, 68 embeddings
emean = e.mean(0, keepdim=True) # (1, 4, 68); mean ONLY over the very first dimension
emean2 = e.mean((0,1), keepdim=True)

emean3 = e.mean(0, keepdim=False) # (4, 68); mean ONLY over the very first dimension
emean4 = e.mean((0,1), keepdim=False) # (68); mean over the first two dimensions

print(emean.shape)  # (1, 4, 68)
print(emean2.shape) # (1, 1, 68)
print(emean3.shape) # (4, 68)
print(emean4.shape) # (68)



torch.Size([1, 4, 68])
torch.Size([1, 1, 68])
torch.Size([4, 68])
torch.Size([68])


In [4]:
e0 = torch.randn(32, 4, 68)
emean0 = e.mean((0,1), keepdim=True)        # 1, 4, 68 ; mean ONLY over the very first dimension
evar0 = e.var((0,1), keepdim=True)          # 1, 4, 68
ehat0 = (e-emean) / torch.sqrt(evar0 + 1e-5) # 32, 4, 68

print(ehat0.shape)

torch.Size([32, 4, 68])


In [24]:
b = torch.arange(6 * 8 * 10).reshape(6, 8, 10)# numbers from 0 to 319, reshaped into a 6x8x10 tensor
b[:, ::2, :]

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]],

        [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

        [[160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
         [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
         [200, 201, 202, 203, 204, 205, 206, 207, 208, 209],
         [220, 221, 222, 223, 224, 225, 226, 227, 228, 229]],

        [[240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
         [260, 261, 262, 263, 264, 265, 266, 267, 268, 269],
         [280, 281, 282, 283, 284, 285, 286, 287, 288, 289],
         [300, 301, 302, 303, 304, 305, 306, 307, 308, 309]],

        [[320, 3

In [19]:
e = torch.arange(6 * 8 * 10).reshape(6, 8, 10)# numbers from 0 to 319, reshaped into a 4x8x10 tensor
print(e)

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]],

        [[160, 161, 

In [20]:
c = torch.arange(6 * 8 * 10).reshape(6, 8, 10)# numbers from 0 to 319, reshaped into a 4x8x10 tensor
c[:, 1::2, :]

tensor([[[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]],

        [[ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]],

        [[170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
         [190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
         [210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
         [230, 231, 232, 233, 234, 235, 236, 237, 238, 239]],

        [[250, 251, 252, 253, 254, 255, 256, 257, 258, 259],
         [270, 271, 272, 273, 274, 275, 276, 277, 278, 279],
         [290, 291, 292, 293, 294, 295, 296, 297, 298, 299],
         [310, 311, 312, 313, 314, 315, 316, 317, 318, 319]],

        [[330, 3

In [21]:
m = torch.arange(6 * 8 * 10).reshape(6, 8, 10)# numbers from 0 to 319, reshaped into a 4x8x10 tensor

explicit = torch.cat([m[:, ::2, :], m[:, 1::2, :]], dim=2) # concatenate the even and odd columns along the last dimension
print(explicit) # 6, 8, 10

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
           14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
           34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
           54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
           74,  75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
           94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
          114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
          134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
          154, 155, 156, 157, 158, 159]],

        [[160, 161, 162, 163

In [25]:
a = torch.arange(6 * 8 * 10).reshape(6, 8, 10) # 6 examples, 8 characters, 10 embeddings
print(a.view(6, 4, 20)) # 6, 4, 20

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
           14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
           34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
           54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
           74,  75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
           94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
          114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
          134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
          154, 155, 156, 157, 158, 159]],

        [[160, 161, 162, 163

In [33]:
B = 6 
T = 8
C = 10
n = 2
t = torch.arange(B * T * C).reshape(B, T, C) # B examples, T characters, C embeddings
v_view = t.view(B, T//n, n*C) # B examples, T/n characters, n*C embeddings
print(v_view.shape) # 6, 4, 20

T = 1
t = torch.arange(B * T * C).reshape(B, T, C) # B examples, T characters, C embeddings
v_view = t.squeeze(1) # remove the second dimension, which is 1
print(v_view.shape) # 6, 20

torch.Size([6, 4, 20])
torch.Size([6, 10])
